# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lesson2_fractal_llm',
                'doc_host': 'https://trangdoan982.github.io',
                'git_url': 'https://github.com/trangdoan982/lesson2_fractal_llm',
                'lib_path': 'lesson2_fractal_llm'},
  'syms': {'lesson2_fractal_llm.core': {'lesson2_fractal_llm.core.foo': ('core.html#foo', 'lesson2_fractal_llm/core.py')}}}
